name: Analyzer

on:
  pull_request:
  push:
    branches: [master]

jobs:
  analyzer:
    name: analyzer
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CARDINAL_ACCESS_TOKEN }}
      - name: Install Dependency
        run: |
          sudo apt update && sudo apt install -y cmake g++ gcc libopenblas-dev  libboost-program-options-dev libaio-dev libcurl4-openssl-dev clang-tidy python3-pip libtbb-dev libtbb2 && pip3 install conan==1.58.0
      - name: Build & Analyzer
        run: |
          mkdir build && cd build && conan install .. --build=missing -o with_ut=True -o with_diskann=True -o with_asan=True && conan build .. \
          && cd .. && find src -type f | grep -E "\.cc$" | xargs /usr/lib/llvm-10/share/clang/run-clang-tidy.py -quiet -p=./build/Release
